version: '3.8'   # Docker Compose 版本

services:        # 定义服务
  dev-environment:  # 服务名称
    build:          # 构建配置
      context: ./ubuntu-local   # Dockerfile所在目录
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    image: my-cpp-project:ubuntu-focal  # 生成的镜像名称
    container_name: my-cpp-dev          # 容器名称
    volumes:
      # 挂载项目目录到容器
      - ..:/workspace                   # .. = 您电脑上的项目目录
                                        # /workspace = 容器内的目录
                                        # : = 建立传送门连接
      # 挂载 ccache 缓存目录（加速编译）
      - ccache-data:/workspace/.ccache
      # 挂载 Git 配置（可选）
      - ${HOME}/.gitconfig:/home/developer/.gitconfig:ro
    working_dir: /workspace #作用: 设置容器启动时的工作目录。
    environment:        # 设置容器内的环境变量。
      # 设置环境变量
      - TERM=xterm-256color
      - CCACHE_DIR=/workspace/.ccache
    # 保持容器运行
    tty: true           # 分配伪终端
    stdin_open: true    # 保持标准输入开放
    # 容器退出后自动重启（除非手动停止）
    restart: unless-stopped
    # 网络端口映射（如果需要）
    # ports:
    #   - "8080:8080"

volumes:
  ccache-data:  # 持久化 ccache 数据